{% set version = "1.0.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-changepoint.np
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/changepoint.np_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/changepoint.np/changepoint.np_{{ version }}.tar.gz
  sha256: c9eeb0be6ec58fc9a44fc5a88a29df4e21430644bcf7d2c28961ae5ac10fd2cf

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rdpack
    - r-changepoint
    - r-zoo
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rdpack
    - r-changepoint
    - r-zoo

test:
  commands:
    - $R -e "library('changepoint.np')"           # [not win]
    - "\"%R%\" -e \"library('changepoint.np')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=changepoint.np
  license: GPL-2.0-or-later
  summary: Implements the multiple changepoint algorithm PELT with a nonparametric cost function based on the empirical distribution of the data. This package extends the changepoint package (see Killick, R and Eckley, I (2014) <doi:10.18637/jss.v058.i03> ).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
